### ISSUE TITLE
got error when "pip install masked_ai"

### ISSUE THREAD

**Issue by ozbillwang** [cado-security/masked-ai#6]
Something wrong with the pip packaging.

>Discarding https://files.pythonhosted.org/packages/1a/a3/df69128e571c66047edcc4d09d015f8c675d045cc6ed0fa61485545710cd/masked_ai-1.0.15.tar.gz (from https://pypi.org/simple/masked-ai/): Requested masked_ai from https://files.pythonhosted.org/packages/1a/a3/df69128e571c66047edcc4d09d015f8c675d045cc6ed0fa61485545710cd/masked_ai-1.0.15.tar.gz (from -r requirements.txt (line 3)) has inconsistent version: expected '1.0.15', but metadata has '0.0.0'

**Comment by ozbillwang** [comment]
I can lock the version to `1.0.14` and `pip install` is successful, then got second issue:

```
ImportError: cannot import name 'Masker' from 'masked_ai'
```

**Comment by chrisdoman** [comment]
Hello, What os and python version are you running please?

I've just tested python3.11 on osx and this works for me (note pip3):

pip3 install install masked_ai

**Comment by ozbillwang** [comment]
![image](https://github.com/cado-security/masked-ai/assets/8954908/ecf00b57-c62e-4d33-92c1-3d7755dd3da2)

**Comment by badlimes** [comment]
> I can lock the version to `1.0.14` and `pip install` is successful, then got second issue:
> 
> ```
> ImportError: cannot import name 'Masker' from 'masked_ai'
> ```


@ozbillwang You have to import it as followed:

`from masked_ai.masker import Masker`

The chosen naming is pretty confusing but you won't get the class without specifying it like that. Atleast on windows i guess.
